### ISSUE TITLE
Recent updates break the extension on Gnome 44

### ISSUE THREAD

**Issue by ditsuke** [ManeLippert/gnome-shell-extension-pop-launcher-super-key#1]
Recent updates break the extension on Gnome 44, here's the error I can see through journalctl/the extension manager:
```
GLib.FileError: Failed to open file “/home/uname/.local/share/gnome-shell/extensions/pop-launcher-super-key@ManeLippert/schemas/gschemas.compiled”: open() failed: No such file or directory
```

**Comment by matissime** [comment]
Same issue on my side.

**Comment by humanplayer2** [comment]
The extension works if you reinstall from the source, but breaks---I guess---do to auto-updating from Gnome Extensions?

@ManeLippert, did you update the Gnome Extensions version to the "long-term support" version you so kindly created?

**Comment by ManeLippert** [comment]
Dear Everyone,

First let me apologise that I did not answer you in the first place. I got the notification form GitHub today...
It looks like my last upload missed the file `gschemas.compiled` I will have a look into that.

@humanplayer2 that was something I tried but they said that I can only upload files with support for the current new version of Gnome, i.e., Gnome 44.

**Comment by ManeLippert** [comment]
Hello @humanplayer2, @matissime, @ditsuke,

The issue should be now solved just the update has to be reviewed on Gnome Extensions. Please Update later :)

Thanks for reaching out to me!

**Comment by humanplayer2** [comment]
No no, *thank you*, @ManeLippert! The extension now does not throw the error. Thank you also for the explanation that you are not allowed to state pre-compatibility on Gnome Extensions.
